### ISSUE TITLE
Failed to build 0.2.2 on Ubuntu 22.04 with `--user`

### ISSUE THREAD

**Issue by lyda** [abetlen/llama-cpp-python#707]
Ran the following on an intel Ubuntu 22.04 system:

```
$ pip3 install --user llama-cpp-python                   Collecting llama-cpp-python
  Using cached llama_cpp_python-0.2.2.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diskcache>=5.6.1
  Using cached diskcache-5.6.3-py3-none-any.whl (45 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /home/lyda@azdsthq.net/.local/lib/python3.10/site-packages (from llama-cpp-python) (4.7.1)
Collecting numpy>=1.20.0
  Using cached numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      *** scikit-build-core 0.5.0 using CMake 3.27.4 (wheel)
      *** Configuring CMake...
      loading initial cache file /tmp/tmp9u4e4cug/build/CMakeInit.txt
      -- The C compiler identification is GNU 11.4.0
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Git: /usr/bin/git (found version "2.41.0")
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      CMake Warning at vendor/llama.cpp/CMakeLists.txt:125 (message):
        Git repository not found; to enable automatic generation of build info,
        make sure Git is installed and the project is a Git repository.
      
      
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- CMAKE_SYSTEM_PROCESSOR: x86_64
      -- x86 detected
      -- Configuring done (0.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/tmp9u4e4cug/build
      *** Building project with Ninja...
      Change Dir: '/tmp/tmp9u4e4cug/build'
      
      Run Build Command(s): /tmp/pip-build-env-l3ehx8u0/normal/local/lib/python3.10/dist-packages/ninja/data/bin/ninja -v
      [1/10] /usr/bin/cc -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -mf16c -mfma -mavx -mavx2 -MD -MT vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o -MF vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o.d -o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o -c /tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/ggml-alloc.c
      [2/10] /usr/bin/c++ -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/common/. -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -mf16c -mfma -mavx -mavx2 -MD -MT vendor/llama.cpp/common/CMakeFiles/common.dir/console.cpp.o -MF vendor/llama.cpp/common/CMakeFiles/common.dir/console.cpp.o.d -o vendor/llama.cpp/common/CMakeFiles/common.dir/console.cpp.o -c /tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/common/console.cpp
      [3/10] /usr/bin/c++ -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/common/. -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -mf16c -mfma -mavx -mavx2 -MD -MT vendor/llama.cpp/common/CMakeFiles/common.dir/grammar-parser.cpp.o -MF vendor/llama.cpp/common/CMakeFiles/common.dir/grammar-parser.cpp.o.d -o vendor/llama.cpp/common/CMakeFiles/common.dir/grammar-parser.cpp.o -c /tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/common/grammar-parser.cpp
      [4/10] /usr/bin/cc -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -mf16c -mfma -mavx -mavx2 -MD -MT vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o -MF vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o.d -o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o -c /tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/k_quants.c
      [5/10] /usr/bin/c++ -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/common/. -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -mf16c -mfma -mavx -mavx2 -MD -MT vendor/llama.cpp/common/CMakeFiles/common.dir/common.cpp.o -MF vendor/llama.cpp/common/CMakeFiles/common.dir/common.cpp.o.d -o vendor/llama.cpp/common/CMakeFiles/common.dir/common.cpp.o -c /tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/common/common.cpp
      [6/10] /usr/bin/cc -DGGML_USE_K_QUANTS -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -mf16c -mfma -mavx -mavx2 -MD -MT vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o -MF vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o.d -o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o -c /tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/ggml.c
      [7/10] : && /usr/bin/cc -fPIC -O3 -DNDEBUG   -shared -Wl,-soname,libggml_shared.so -o vendor/llama.cpp/libggml_shared.so vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o   && :
      [8/10] : && /tmp/pip-build-env-l3ehx8u0/normal/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -E rm -f vendor/llama.cpp/libggml_static.a && /usr/bin/ar qc vendor/llama.cpp/libggml_static.a  vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o && /usr/bin/ranlib vendor/llama.cpp/libggml_static.a && :
      [9/10] /usr/bin/c++ -DGGML_USE_K_QUANTS -DLLAMA_BUILD -DLLAMA_SHARED -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -Dllama_EXPORTS -I/tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/. -O3 -DNDEBUG -std=gnu++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -mf16c -mfma -mavx -mavx2 -MD -MT vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o -MF vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o.d -o vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o -c /tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/vendor/llama.cpp/llama.cpp
      [10/10] : && /usr/bin/c++ -fPIC -O3 -DNDEBUG   -shared -Wl,-soname,libllama.so -o vendor/llama.cpp/libllama.so vendor/llama.cpp/CMakeFiles/ggml.dir/ggml.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/ggml-alloc.c.o vendor/llama.cpp/CMakeFiles/ggml.dir/k_quants.c.o vendor/llama.cpp/CMakeFiles/llama.dir/llama.cpp.o   && :
      
      *** Installing project into wheel...
      -- Install configuration: "Release"
      -- Installing: /tmp/tmp9u4e4cug/wheel/platlib/lib/libggml_shared.so
      -- Installing: /tmp/tmp9u4e4cug/wheel/platlib/lib/libllama.so
      -- Installing: /tmp/tmp9u4e4cug/wheel/platlib/bin/convert.py
      -- Installing: /tmp/tmp9u4e4cug/wheel/platlib/bin/convert-lora-to-ggml.py
      -- Installing: /tmp/tmp9u4e4cug/wheel/platlib/llama_cpp/libllama.so
      -- Installing: /tmp/pip-install-2zaya40h/llama-cpp-python_6d3abaf7e49f4232888c7f28a96156a1/llama_cpp/libllama.so
      *** Making wheel...
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-l3ehx8u0/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/__init__.py", line 32, in build_wheel
          return _build_wheel_impl(
        File "/tmp/pip-build-env-l3ehx8u0/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/wheel.py", line 261, in _build_wheel_impl
          mapping = packages_to_file_mapping(
        File "/tmp/pip-build-env-l3ehx8u0/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/_pathutil.py", line 43, in packages_to_file_mapping
          for filepath in each_unignored_file(
        File "/tmp/pip-build-env-l3ehx8u0/overlay/local/lib/python3.10/dist-packages/scikit_build_core/build/_file_processor.py", line 41, in each_unignored_file
          exclude_spec = pathspec.GitIgnoreSpec.from_lines(exclude_lines)
      AttributeError: module 'pathspec' has no attribute 'GitIgnoreSpec'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

**Comment by abetlen** [comment]
Hmm can you try to do `pip3 install --user --upgrade pathspec` and then try to reinstall. I think you may have an older version installed and a build dependency has  an insufficient minimum version.

**Comment by abetlen** [comment]
@lyda can you give `0.2.3` a try I implemented a potential fix.

**Comment by lyda** [comment]
Annoyingly python's default module path uses system modules over user ones.  Which seems broken.  I had to remove `python3-pathspec` - which is a dependency of a utility I use called `yamllint`.  So I did this:

```bash
sudo apt remove python3-pathspec
pip3 install --user pathspec yamllint
```

Then I just did `pip3 install --user --upgrade llama-cpp-python` and it worked just fine - 0.2.4 was installed so you did a new release in the past 7 hours.  Nice.

Thanks!

And in case anyone reads this trying to figure out issues with their `pip install --user` stuff, another thing to check is to make sure `$HOME/.local/bin` is in your `$PATH` - and that you've done an `export PATH`.

Also, you can run `pip3 show llama-cpp-python` to see the dependencies and then make sure you don't have them installed on the system via `apt search the-dependency-you-are-curious-about` which will usually work (adjust to your system's packaging system).

Good luck future reader!

**Comment by playerjamesbattleground** [comment]
I have exactly the same issue re above with pathsec.GitignoreSec , while building wheels. 

What's in different is i'm installing the llama-cpp-python package onto a single node compute cluster on Azure Databricks. The g++ version is up to date and i've also tried remov ethe apt pathsec, but so far still no luck as same issues still repeats.

**Comment by playerjamesbattleground** [comment]
Update:

I worked it around by using workspace package installation (i.e install python package by PyPI from databrick compute's 'Library' tab)
with 
pathspec==0.11.0 to make it notebook aware

then when i'm installing llama-cpp-python again from notebook, it will pick the right version of pathspec and built successfully

**Comment by LecrisUT** [comment]
This seems like a bug within `pip` itself where build-isolation is not properly isolated. We hit this in `scikit-build-core`, but `python3 -m build` or `uv pip install` do not seem to be affected. I've opened [an issue](https://github.com/pypa/pip/issues/12976) on this.

**Comment by henryiii** [comment]
Also, installing anything with `--user` can really mess things up. I strongly recommend always using virtual environments and never installing to system or user unless you are in a docker container or some other throw-away system. The "uv pip" command, from uv, a Rust reimplementations of much of Python packaging, literally won't let you install to user due to how easy it is to break your system doing so.
